name: CI

env:
  MAJOR_TAG: "v1"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Update major tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -d ${{ env.MAJOR_TAG }} || true
          git push --delete origin ${{ env.MAJOR_TAG }} || true
          git push origin :refs/tags/${{ env.MAJOR_TAG }}
          git tag ${{ env.MAJOR_TAG }}
          git push --tags
